{{ if not (eq .Values.imagePullCredentials.registry "empty.empty") }}

apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{end}}