{{ range $redis := .Values.redis }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-{{ $redis.name }}-{{ $.Values.projectName }}
  labels:
    app: redis-{{ $redis.name }}-{{ $.Values.projectName }}
spec:
  selector:
    matchLabels:
      app: redis-{{ $redis.name }}-{{ $.Values.projectName }}
  template:
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
    metadata:
      labels:
        app: redis-{{ $redis.name }}-{{ $.Values.projectName }}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-{{ $redis.name }}-{{ $.Values.projectName }}
  labels:
    app: redis-{{ $redis.name }}-{{ $.Values.projectName }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-{{ $redis.name }}-{{ $.Values.projectName }}

{{end}}